# Generated by Django 4.2.1 on 2023-05-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Mode',
        ),
    ]
