# Generated by Django 4.2.1 on 2023-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_and_quantity',
            field=models.JSONField(default={}),
        ),
    ]
