# Generated by Django 4.2.1 on 2023-05-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='mode',
        ),
        migrations.AddField(
            model_name='menu',
            name='mode',
            field=models.ManyToManyField(to='Menu.mode'),
        ),
    ]
