# Generated by Django 4.2.1 on 2023-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_menu_and_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_and_quantity',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('checking', 'checking'), ('in_progress', 'in_progress'), ('done', 'done')], max_length=100),
        ),
    ]
