# Generated by Django 4.2.1 on 2023-05-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_rename_order_mode'),
        ('Order', '0004_alter_order_menu_and_quantity_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_and_quantity',
        ),
        migrations.CreateModel(
            name='Ordered_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
    ]
